module DepositApp 
{
	interface Deposit
	{
		string sayHello();
		void addProd(in long quant, in long type);
		void remProd(in long quant, in long type);
		long showProd(in long type);
		//oneway void shutdown();
	};
};