package EmailApp;


/**
* EmailApp/EmailOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Email.idl
* Sunday, November 25, 2018 3:49:42 PM BRST
*/

public interface EmailOperations 
{
  String sayHello ();
  String message (String msg);
  void shutdown ();
} // interface EmailOperations
