package EmailApp;


/**
* EmailApp/EmailPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Email.idl
* Sunday, November 25, 2018 3:49:42 PM BRST
*/

public abstract class EmailPOA extends org.omg.PortableServer.Servant
 implements EmailApp.EmailOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sayHello", new java.lang.Integer (0));
    _methods.put ("message", new java.lang.Integer (1));
    _methods.put ("shutdown", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // EmailApp/Email/sayHello
       {
         String $result = null;
         $result = this.sayHello ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // EmailApp/Email/message
       {
         String msg = in.read_string ();
         String $result = null;
         $result = this.message (msg);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // EmailApp/Email/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:EmailApp/Email:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Email _this() 
  {
    return EmailHelper.narrow(
    super._this_object());
  }

  public Email _this(org.omg.CORBA.ORB orb) 
  {
    return EmailHelper.narrow(
    super._this_object(orb));
  }


} // class EmailPOA
