package EmailApp;

/**
* EmailApp/EmailHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Email.idl
* Sunday, November 25, 2018 3:49:42 PM BRST
*/

public final class EmailHolder implements org.omg.CORBA.portable.Streamable
{
  public EmailApp.Email value = null;

  public EmailHolder ()
  {
  }

  public EmailHolder (EmailApp.Email initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EmailApp.EmailHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EmailApp.EmailHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EmailApp.EmailHelper.type ();
  }

}
