package EmailApp;


/**
* EmailApp/Email.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Email.idl
* Sunday, November 25, 2018 3:49:42 PM BRST
*/

public interface Email extends EmailOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Email
