package DepositApp;


/**
* DepositApp/Deposit.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Deposit.idl
* Monday, November 26, 2018 8:36:24 PM BRST
*/

public interface Deposit extends DepositOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Deposit
