package DepositApp;


/**
* DepositApp/DepositPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Deposit.idl
* Monday, November 26, 2018 11:26:33 AM BRST
*/

public abstract class DepositPOA extends org.omg.PortableServer.Servant
 implements DepositApp.DepositOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sayHello", new java.lang.Integer (0));
    _methods.put ("addProd", new java.lang.Integer (1));
    _methods.put ("remProd", new java.lang.Integer (2));
    _methods.put ("showProd", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DepositApp/Deposit/sayHello
       {
         String $result = null;
         $result = this.sayHello ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DepositApp/Deposit/addProd
       {
         double quant = in.read_double ();
         double type = in.read_double ();
         this.addProd (quant, type);
         out = $rh.createReply();
         break;
       }

       case 2:  // DepositApp/Deposit/remProd
       {
         double quant = in.read_double ();
         double type = in.read_double ();
         this.remProd (quant, type);
         out = $rh.createReply();
         break;
       }

       case 3:  // DepositApp/Deposit/showProd
       {
         double type = in.read_double ();
         double $result = (double)0;
         $result = this.showProd (type);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 4:  // DepositApp/Deposit/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DepositApp/Deposit:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Deposit _this() 
  {
    return DepositHelper.narrow(
    super._this_object());
  }

  public Deposit _this(org.omg.CORBA.ORB orb) 
  {
    return DepositHelper.narrow(
    super._this_object(orb));
  }


} // class DepositPOA
