package DepositApp;


/**
* DepositApp/Deposit.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Deposit.idl
* Sunday, November 25, 2018 11:51:23 PM BRST
*/

public interface Deposit extends DepositOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Deposit
