package DepositApp;


/**
* DepositApp/DepositOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Deposit.idl
* Sunday, December 9, 2018 9:18:42 PM BRST
*/

public interface DepositOperations 
{
  String sayHello ();
  void addProd (int quant, int type);
  void remProd (int quant, int type);
  int showProd (int type);
} // interface DepositOperations
