package DepositApp;


/**
* DepositApp/DepositOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Deposit.idl
* Monday, November 26, 2018 11:26:33 AM BRST
*/

public interface DepositOperations 
{
  String sayHello ();
  void addProd (double quant, double type);
  void remProd (double quant, double type);
  double showProd (double type);
  void shutdown ();
} // interface DepositOperations
