package DepositApp;


/**
* DepositApp/Deposit.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Deposit.idl
* Thursday, December 6, 2018 5:58:50 PM BRST
*/

public interface Deposit extends DepositOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Deposit
